#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BluetoothChat.Resource", IsApplication=true)]

namespace BluetoothChat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int button_scan = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int discoverable = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int new_devices = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int paired_devices = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int scan = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int title_left_text = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int title_new_devices = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int title_paired_devices = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int title_right_text = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int webView1 = 2131099655;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int custom_title = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int device_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int device_name = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int message = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int option_menu = 2131034112;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int bt_not_enabled_leaving = 2130968579;
			
			// aapt resource value: 0x7f04000d
			public const int button_scan = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int connect = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int discoverable = 2130968591;
			
			// aapt resource value: 0x7f04000a
			public const int none_found = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int none_paired = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int not_connected = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int scanning = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int select_device = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int send = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int title_connected_to = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int title_connecting = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int title_not_connected = 2130968582;
			
			// aapt resource value: 0x7f04000c
			public const int title_other_devices = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int title_paired_devices = 2130968587;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
